global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'default'

receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://localhost:9090'
