global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname']
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: ''
        send_resolved: true

