version: '3.3'

services:
  reactapp:
    build:
      context: .
    ports:
      - "80:80"
    networks:
      - my-network
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  express-server:
    build:
      context: ./express-server
    ports:
      - "3010:3010"
    networks:
      - my-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - my-network

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - my-network 

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    networks:
      - my-network
    depends_on:
      - express-server
      - reactapp
      - node-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    networks:
      - my-network
    depends_on:
      - prometheus

networks:
  my-network:
    driver: bridge

